### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by MatthewVita** [EntelekiaLearning/Website#10]
Tim,

We have to configure SemanticUI to render icons correctly (I can do this).

I actually never use Semantic's icons though... the library I use (and most do as it's defacto) is http://fortawesome.github.io/Font-Awesome/ It's easy to get up and running with as opposed to configuring Semantic's icon location stuff and I think it's a superior library for icons.

Let me know how you want to move forward

**Comment by timothyfcook** [comment]
I've heard good things about font awesome. Let's go with that if you prefer.

**Comment by MatthewVita** [comment]
https://github.com/EntelekiaLearning/Website/commit/eae37f73f1d219f0c954f46e0e5b84fa4365e9b7
