### ISSUE TITLE
run.sh error

### ISSUE THREAD

**Issue by timothyfcook** [EntelekiaLearning/Website#14]
![screen shot 2015-01-15 at 9 31 19 am](https://cloud.githubusercontent.com/assets/1823300/5759127/59f0b124-9c99-11e4-99c7-ae13588603ff.png)

might be my fault?

**Comment by MatthewVita** [comment]
Can't reproduce :(

Can you show me the exact commands you're issuing?

**Comment by timothyfcook** [comment]
ran sudo ./install.sh first and got this:

then ran ./run.sh and got the one i already posted.

**Comment by MatthewVita** [comment]
Your screenshot didn't post in the most recent comment... so I'm commenting without that info.

`cd` to your project's `Website` dir and issue:
`sudo npm cache clean & bower cache clean`

Do you have the latest code? In other words, when's the last time you `git pull origin master`?

**Comment by MatthewVita** [comment]
and this is all in `Website/`, correct?

**Comment by timothyfcook** [comment]
Tried cleaning the cache, didn't work. Git was up to date with origin master.

Just deleted the repo and re-cloned. Seems to work now. Weird.

"have you tried turning it off and on again?"

: )

**Comment by MatthewVita** [comment]
https://www.youtube.com/watch?v=ms0CwcJlY5U

**Comment by timothyfcook** [comment]
: ) !!!!!!
