### ISSUE TITLE
Neo4j v. Cayley

### ISSUE THREAD

**Issue by MatthewVita** [EntelekiaLearning/Website#5]
Tim,

UPDATE: Actually I spoke too soon... I just found a really mature and idiomatic Python Neo4j library: https://github.com/versae/neo4j-rest-client

It:
a. doesn't use Cypher notation (it instead uses a more idiomatic Python API wrapper, which is a plus)
b. is more mature than the Cayley python library.

Looks like it's Neo4j afterall :+1:

**Comment by MatthewVita** [comment]
@timothyfcook bump

**Comment by timothyfcook** [comment]
Thought this might wind up being the case. Nice research. Sounds good to me. What's the story on using neo4j? Is it free to start out? Any open source aspects to it?

**Comment by timothyfcook** [comment]
Found this on their page: "Neo4j is an open source product. We support a Community edition under the GPLv3 license. The Enterprise edition is available under the AGPLv3 license for open source projects otherwise under a commercial license from Neo Technology."

**Comment by MatthewVita** [comment]
:+1:

**Comment by timothyfcook** [comment]
Sounds like we are good moving forward, though we may want to revisit this and look at the parameters of the AGPLv3 license if and when we start using the Enterprise edition. Especially if this project gains traction, becomes used by other cities, or makes any money: http://www.fsf.org/news/agplv3-pr

**Comment by timothyfcook** [comment]
Can we close this out? Feel good about Neo4j?

**Comment by MatthewVita** [comment]
yep
