### ISSUE TITLE
Browser Requirements

### ISSUE THREAD

**Issue by MatthewVita** [EntelekiaLearning/Website#7]
Tim,

What do you think the browser requirements should be for Entelekia? Obviously most people are using modern browsers (chrome, firefox, IE11+, etc) but there are still people on old IEs :(

The most "demanding" browser requirements on the frontend is SemanticUI's IE9 and greater requirement.

I'm okay with the requirement being IE9+ and having a warning in place for legacy browsers, but if you want to support IE8 (which isn't that uncommon) we will have to swap out SemanticUI for Bootstrap (which is okay, I just prefer SemanticUI really).

(BTW, I'll document the final requirement decision in the "App Info" wiki entry)

**Comment by timothyfcook** [comment]
Agreed. I'm okay with being unfriendly to the oldest browsers if it improves our product capabilities. Especially since we won't have tons of users right now. By the time Entelekia becomes huge everyone will be using new browsers anyhow!

**Comment by timothyfcook** [comment]
IE9+ it is!

**Comment by MatthewVita** [comment]
https://github.com/EntelekiaLearning/Website/wiki/App-Info#browser-requirements
