### ISSUE TITLE
create one file for all "white label" variables

### ISSUE THREAD

**Issue by timothyfcook** [EntelekiaLearning/Website#8]
I suggested some new variables in the `<meta property="og:image" content="logo.png">` tags, for easy transitions to new names we could create a single whitelabel-variables file to allow "Entelekia" to be swapped for "learnpgh" or "learnnyc" down the road.

**Comment by MatthewVita** [comment]
Check out the template variables issue. We can add in a Jade include file for things like this, sure

**Comment by MatthewVita** [comment]
so we good here?

**Comment by timothyfcook** [comment]
excellent.
