### ISSUE TITLE
Homepage Template Variables

### ISSUE THREAD

**Issue by MatthewVita** [EntelekiaLearning/Website#9]
Tim,

Let me know what the variables for homepage should be (if we have them at the moment).

Thanks

**Comment by timothyfcook** [comment]
We may run into more, here's what I have so far:

<Facebook Opengraph Info>
var = og_title (content = "Entelekia: A Citywide Knowledge Map")
var = og_description (content = "One place to find all of the resources you need to learn about anything.
var = og_url (content = "http://www.entelekia.org")
var = og_image (content = "resources/images/learnpgh_logo.png")

<Others>
var = title (content = "Entelekia")
var = twitter_link (content = "https://www.twitter.com/learnpgh)
var = city (content = "Pittsburgh")
var = city_shortcode (content = "pgh")

These are variable names, as well as what the value for each variable for be for our purposes to start out. I can these all being global variables across all pages. I'm sure we'll think of more.

Is this what you were looking for?

**Comment by MatthewVita** [comment]
Great. I'll get these set up in `conf.py`

**Comment by MatthewVita** [comment]
https://github.com/EntelekiaLearning/Website/commit/ab981379e06f1426e0c73ae5f1478d86f1a77f1c
 and https://github.com/EntelekiaLearning/Website/commit/e8f3e0c50f30e74aedab6a1377e5b9b58910a6a2
feel free to close this task once you QA

**Comment by timothyfcook** [comment]
looks great.
